#!/bin/bash

SEMVER_REGEX="^v(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$"

if [[ "$TRAVIS_TAG" =~ $SEMVER_REGEX ]]; then
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  docker push $DOCKER_ORG/$IMAGE_NAME
elif [[ "$TRAVIS_BRANCH" == "master" ]]; then
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  docker tag $DOCKER_ORG/$IMAGE_NAME $DOCKER_ORG/$IMAGE_NAME:test
  docker push $DOCKER_ORG/$IMAGE_NAME:test
else
  echo "Do not deploy. This is neither the master branch nor a release."
fi
