#!/bin/bash

echo """
*****************************
* docker_push version 1.1.0 *
*****************************

---------------------------
| Information from Travis
---------------------------
| Repository: $TRAVIS_REPO_SLUG
| Branch: $TRAVIS_BRANCH
| Commit: $TRAVIS_COMMIT
| TRAVIS_EVENT_TYPE: $TRAVIS_EVENT_TYPE
| TRAVIS_TAG: $TRAVIS_TAG
| TRAVIS_R_VERSION: $TRAVIS_R_VERSION
---------------------------

Ready to run script...
"""

SEMVER_REGEX="^v(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$"

if [[ "$TRAVIS_TAG" =~ $SEMVER_REGEX ]]; then
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  docker push $DOCKER_ORG/$IMAGE_NAME
elif [[ "$TRAVIS_BRANCH" == "master" ]]; then
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  docker tag $DOCKER_ORG/$IMAGE_NAME $DOCKER_ORG/$IMAGE_NAME:master
  docker push $DOCKER_ORG/$IMAGE_NAME:master
else
  echo "Do not deploy. This is neither the master branch nor a release."
fi
